=head1 NAME

SOAP::Lite::Manual::Cookbook - Cooking with SOAP::Lite

=head1 DESCRIPTION

Some SOAP::Lite code recipes for busy developers on the go.

=head1 RECIPES FOR CLIENTS

=head2 Enabling HTTP keepalive

You can switch on keepalive by adding C<keepalive> to your ->proxy 
arguments:

 my $soap = SOAP::Lite->proxy('http://example.org', keepalive => 1);

=head2 SOAP client for document/literal .NET web services

=head3 Example

  use SOAP::Lite;
 
  my $uri = 'http://www.webserviceX.NET';
  my $url = 'http://www.webservicex.net/globalweather.asmx';
  
  my $soap = SOAP::Lite
            -> uri($uri)
            -> on_action( sub { join '/', $uri, $_[1] } )
            -> proxy($url)
            -> autotype(0);
  
  my $method = SOAP::Data->name('GetWeather')->attr({xmlns => $uri});
  
  my $result = $soap->call($method => (
                SOAP::Data->name('CityName')->value('Cambridge'),
                SOAP::Data->name('CountryName')->value('United Kingdom'),)
              );

You should now have a L<SOAP::SOM> result object.

=head1 ADD A RECIPE

If you have a recipe that would save someone hours of futile trial and error 
send it to recipes@soaplite.net (with a working example please) and get it 
added to the cookbook.

=head1 COPYRIGHT

This library is free software. You may distribute/modify it under
the same terms as Perl itself

=head1 AUTHORS

Martin Kutter E<lt>martin.kutter fen-net.deE<gt>

Robbie Bow robbiebow@gmail.com

=cut
